name: Build and Test

# This workflow is triggered on push to the main branch, pull request to the main branch, or manual workflow dispatch
# It runs tests on macOS and Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: oven-sh/setup-bun@123c6c4e2fea3eb7bffaa91a85eb6b3d505bf7af # v2
        with:
          bun-version: latest
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: bun install
      - run: bun run build
      # - run: bun run format-check
      # - run: bun run lint
      - run: bun test
